// One-time generator for app/components/dotmap-data.js, the dot-matrix world
// map used on the home hero. Natural Earth 110m land (public domain, via the
// world-atlas package) rasterized to an equirectangular grid: each land cell
// becomes one dot in the component. Run with land-110m.json in the repo root:
//
//   curl -sL https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json -o land-tmp.json
//   node scripts/generate-dotmap.mjs && rm land-tmp.json
import { readFileSync, writeFileSync } from 'node:fs';

const topo = JSON.parse(readFileSync('land-tmp.json', 'utf8'));

// Decode delta-encoded integer arcs into absolute coordinates.
function decodeArcs(t) {
  const { scale: [sx, sy], translate: [tx, ty] } = t.transform;
  return t.arcs.map((arc) => {
    let x = 0;
    let y = 0;
    return arc.map(([dx, dy]) => {
      x += dx;
      y += dy;
      return [x * sx + tx, y * sy + ty];
    });
  });
}

const arcs = decodeArcs(topo);

// A ring referenced by a list of arc indices; negative i means arc ~i reversed.
function ringFromArcs(ids) {
  const pts = [];
  for (const id of ids) {
    const arc = id < 0 ? [...arcs[~id]].reverse() : arcs[id];
    // Adjacent arcs share their joint vertex; drop the first point of every
    // arc after the first to avoid duplicates.
    pts.push(...(pts.length ? arc.slice(1) : arc));
  }
  return pts;
}

const land = topo.objects.land.geometries.find((g) => g.type === 'MultiPolygon');
const rings = [];
for (const poly of land.arcs) {
  for (const part of poly) rings.push(ringFromArcs(part));
}

const bboxes = rings.map((r) => {
  let minX = Infinity; let minY = Infinity; let maxX = -Infinity; let maxY = -Infinity;
  for (const [x, y] of r) {
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (x > maxX) maxX = x;
    if (y > maxY) maxY = y;
  }
  return { minX, minY, maxX, maxY };
});

// Even-odd ray casting; holes (lakes) naturally toggle back out.
function inside(lon, lat) {
  let odd = false;
  for (let i = 0; i < rings.length; i++) {
    const b = bboxes[i];
    if (lon < b.minX || lon > b.maxX || lat < b.minY || lat > b.maxY) continue;
    const r = rings[i];
    for (let j = 0, k = r.length - 1; j < r.length; k = j++) {
      const [xi, yi] = r[j];
      const [xk, yk] = r[k];
      if ((yi > lat) !== (yk > lat) && lon < ((xk - xi) * (lat - yi)) / (yk - yi) + xi) {
        odd = !odd;
      }
    }
  }
  return odd;
}

// Equirectangular grid. Antarctica is cropped (lat floor -56 keeps the tip of
// South America); Greenland's north reaches 83.6 so the ceiling is 84.
const COLS = 112;
const ROWS = 50;
const LON_MIN = -180;
const LON_MAX = 180;
const LAT_MIN = -56;
const LAT_MAX = 84;

const rows = [];
for (let r = 0; r < ROWS; r++) {
  const lat = LAT_MAX - ((r + 0.5) / ROWS) * (LAT_MAX - LAT_MIN);
  let line = '';
  for (let c = 0; c < COLS; c++) {
    const lon = LON_MIN + ((c + 0.5) / COLS) * (LON_MAX - LON_MIN);
    line += inside(lon, lat) ? '1' : '0';
  }
  rows.push(line);
}

const out = `// Generated by scripts/generate-dotmap.mjs from Natural Earth 110m land
// (public domain, via npm world-atlas). Each '1' is one dot of the hero's
// dot-matrix world map. Regenerate, do not hand-edit.
export const DOTMAP = { cols: ${COLS}, rows: ${JSON.stringify(rows)} };
`;
writeFileSync('app/components/dotmap-data.js', out);
const dots = rows.join('').replace(/0/g, '').length;
console.log(`wrote app/components/dotmap-data.js: ${COLS}x${ROWS} grid, ${dots} dots`);
